on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Who to greet?'
        default: 'World'

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - id: hello
        uses: ./
        with:
          who-to-greet: ${{ github.event.inputs.name }}
      - run: echo random-number ${{ steps.hello.outputs.random-number }}
        shell: bash
